### ISSUE TITLE
"service_message_history() is not started"

### ISSUE THREAD

**Issue by re2005** [bitdust-io/devel#545]
When BitDust is ready to go, the chat history is not ready.

Can this be solved on the core, instead of on the FE ?

**Comment by vesellov** [comment]
this error means the messaging service is not ready to be used... this is a message history stored on suppliers... most probably at that moment something was not working properly with other services required for `service_message_history()` to be on. 

Lets check the services tree: https://bitdust.io/wiki/services.html  message history is very bellow and requires `my_data()` service... usually it starts slower than `private_messages()` and probably because of that you see that error...

what we can do is to return another HTTP error code for such errors so FE can understand that it just needs to wait.

what do you think @re2005 ?

**Comment by re2005** [comment]
I see, so we may change the FE and only try to fetch history, or even show the CHAT at all when the service is running.
I just need a way to ping the core and get when service is running fine

**Comment by vesellov** [comment]
I think the best way is to drive UI same way as the engine works... some parts/components of the UI might not be available at the same time when other parts are available.   is it possible for you to try to handle that in a generic way?... say if any API call returns you a certain status code you handle that and display related component with spinner, or display "loading..." label?  I mean those kind of situations we will see more and more across the application probably. For example Imagine we will connect BitDust to the blockchain - there could be situation when user is not able to send a transaction yet because sync is in progress, but he still can see his current wallet ID and some other details related to the blockchain. if you just completely disable the blockchain page in the UI until it is available it can be confusing and not friendly... I know it is more work probably to split components like that, but we can try to find the simple way to do that in the UI if you like...  otherwise you can indeed handle such response code and just disable the whole chat component till message history is available. you can also call to  `service_info` API method : https://bitdust.io/wiki/api.html#service_info  - this should give you current state of the service.... but i believe this is redundant for you

**Comment by vesellov** [comment]
another 2 improvements i found here: 

1. websocket connection created from JS code can have an extra callback executed when connection is lost - that means main process stopped and JS code can automatically redirect user to the "dead" screen... so potentially no need for regular "process_health" api calls at all...

2. websocket will show events like : "service_message_history_state ON", "service_message_history_state OFF"
front-end may listen to those and automatically 'disable/enable' corresponding components/pages for user...

**Comment by vesellov** [comment]
In the new p2p app that is currently developing using Kivy framework we have a new UI component that helps to keep track of state machines updeates. This way UI suppose to stay in sync with the engine and make possible to avoid situations when some service is not started yet, but UI is displaying blocked/unready component: https://github.com/bitdust-io/p2p-app/blob/master/src/components/status_panel.py 
I am going to close that issue as it suppose to be already resolved in the new application.
